"use client";

/** Stable 4×4 renderer with permanent cubies, outer turns, and wide turns. */
import {Canvas,useFrame} from "@react-three/fiber";
import {OrbitControls,RoundedBox} from "@react-three/drei";
import {memo,useCallback,useEffect,useMemo,useRef} from "react";
import * as THREE from "three";

type Axis="x"|"y"|"z"; type Cell={x:number;y:number;z:number};
type MoveSpec={axis:Axis;layers:number[];angle:number};
type Record4={group:THREE.Group;matrix:THREE.Matrix4};
type Animation=MoveSpec&{startedAt:number;nextStep:number;cubies:Record4[]};
const POS=[-1.5,-.5,.5,1.5],STEP=.66,SIZE=.62,STICK=.574,OFFSET=.316;
const COLOR={U:"#f7f7f2",R:"#e53935",F:"#24c45a",D:"#ffd21f",L:"#ff7a18",B:"#1464e8"};
const BASE:Record<string,{axis:Axis;outer:number;clockwise:number}>={U:{axis:"y",outer:1.5,clockwise:-1},D:{axis:"y",outer:-1.5,clockwise:1},F:{axis:"z",outer:1.5,clockwise:-1},B:{axis:"z",outer:-1.5,clockwise:1},R:{axis:"x",outer:1.5,clockwise:-1},L:{axis:"x",outer:-1.5,clockwise:1}};
const CELLS:Cell[]=[];for(const x of POS)for(const y of POS)for(const z of POS)CELLS.push({x,y,z});
const invert=(m:string)=>m.endsWith("2")?m:m.endsWith("'")?m.slice(0,-1):`${m}'`;
function spec(move:string):MoveSpec{const face=move[0],b=BASE[face],wide=move.includes("w"),turns=move.endsWith("2")?2:move.endsWith("'")?-1:1,inner=b.outer>0?.5:-.5;return{axis:b.axis,layers:wide?[b.outer,inner]:[b.outer],angle:b.clockwise*turns*Math.PI/2}}
const rotation=(a:Axis,n:number)=>a==="x"?new THREE.Matrix4().makeRotationX(n):a==="y"?new THREE.Matrix4().makeRotationY(n):new THREE.Matrix4().makeRotationZ(n);
const coordinate=(m:THREE.Matrix4,a:Axis)=>m.elements[a==="x"?12:a==="y"?13:14]/STEP;
function snap(m:THREE.Matrix4){const n=m.clone(),e=n.elements;for(const i of [0,1,2,4,5,6,8,9,10])e[i]=Math.abs(e[i])<.5?0:e[i]>0?1:-1;for(const i of [12,13,14])e[i]=Math.round((e[i]/STEP)*2)/2*STEP;e[3]=e[7]=e[11]=0;e[15]=1;return n}
function initialMatrix(cell:Cell,scramble:string){let m=new THREE.Matrix4().makeTranslation(cell.x*STEP,cell.y*STEP,cell.z*STEP);for(const move of scramble.trim().split(/\s+/).filter(Boolean)){const s=spec(move),c=coordinate(m,s.axis);if(s.layers.some(v=>Math.abs(c-v)<.1))m=snap(new THREE.Matrix4().multiplyMatrices(rotation(s.axis,s.angle),m))}return m}
function Sticker({color,position,rotation:[rx,ry,rz]=[0,0,0]}:{color:string;position:[number,number,number];rotation?:[number,number,number]}){return <RoundedBox args={[STICK,STICK,.032]} radius={.035} smoothness={2} position={position} rotation={[rx,ry,rz]}><meshStandardMaterial color={color} roughness={.34}/></RoundedBox>}
const Cubie=memo(function Cubie({cell,scramble,register}:{cell:Cell;scramble:string;register:(k:string,g:THREE.Group|null)=>void}){const{x,y,z}=cell,key=`${x}:${y}:${z}`,matrix=useMemo(()=>initialMatrix(cell,scramble),[cell,scramble]),ref=useCallback((g:THREE.Group|null)=>register(key,g),[key,register]);return <group ref={ref} matrixAutoUpdate={false} matrix={matrix}><RoundedBox args={[SIZE,SIZE,SIZE]} radius={.045} smoothness={2}><meshStandardMaterial color="#111318" roughness={.43}/></RoundedBox>{x===1.5&&<Sticker color={COLOR.R} position={[OFFSET,0,0]} rotation={[0,Math.PI/2,0]}/>} {x===-1.5&&<Sticker color={COLOR.L} position={[-OFFSET,0,0]} rotation={[0,Math.PI/2,0]}/>} {y===1.5&&<Sticker color={COLOR.U} position={[0,OFFSET,0]} rotation={[Math.PI/2,0,0]}/>} {y===-1.5&&<Sticker color={COLOR.D} position={[0,-OFFSET,0]} rotation={[Math.PI/2,0,0]}/>} {z===1.5&&<Sticker color={COLOR.F} position={[0,0,OFFSET]}/>} {z===-1.5&&<Sticker color={COLOR.B} position={[0,0,-OFFSET]}/>}</group>});
function Scene({scramble,solution,step,onAnimating,speed}:{scramble:string;solution:string[];step:number;onAnimating:(v:boolean)=>void;speed:number}){const cubies=useRef(new Map<string,THREE.Group>()),shown=useRef(0),active=useRef<Animation|null>(null),callback=useRef(onAnimating),speedRef=useRef(speed);useEffect(()=>{callback.current=onAnimating},[onAnimating]);useEffect(()=>{speedRef.current=speed},[speed]);const register=useCallback((k:string,g:THREE.Group|null)=>g?cubies.current.set(k,g):cubies.current.delete(k),[]);useEffect(()=>{shown.current=0;active.current=null;callback.current(false)},[scramble]);useEffect(()=>{if(step===shown.current||active.current)return;const forward=step>shown.current,move=forward?solution[shown.current]:invert(solution[shown.current-1]);if(!move)return;const target=spec(move),nextStep=forward?shown.current+1:shown.current-1,selected=Array.from(cubies.current.values()).filter(g=>target.layers.some(v=>Math.abs(coordinate(g.matrix,target.axis)-v)<.1)).map(group=>({group,matrix:group.matrix.clone()}));const expected=target.layers.length*16;if(selected.length!==expected){console.error(`4x4 selected ${selected.length}; expected ${expected}`);return}active.current={...target,startedAt:performance.now(),nextStep,cubies:selected};callback.current(true)},[step,solution]);useFrame(()=>{const a=active.current;if(!a)return;const t=Math.min(1,(performance.now()-a.startedAt)/(460/Math.max(.25,speedRef.current))),e=t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2,r=rotation(a.axis,a.angle*e);for(const c of a.cubies){c.group.matrix.multiplyMatrices(r,c.matrix);c.group.matrixWorldNeedsUpdate=true}if(t>=1){const done=rotation(a.axis,a.angle);for(const c of a.cubies){c.group.matrix.copy(snap(new THREE.Matrix4().multiplyMatrices(done,c.matrix)));c.group.matrixWorldNeedsUpdate=true}shown.current=a.nextStep;active.current=null;callback.current(false)}});return <><hemisphereLight args={["#fff","#18345f",1.45]}/><directionalLight position={[5,8,7]} intensity={1.75}/><group rotation={[-.08,-.08,0]} scale={.9}>{CELLS.map(c=><Cubie key={`${scramble}:${c.x}:${c.y}:${c.z}`} cell={c} scramble={scramble} register={register}/>)}</group><OrbitControls enablePan={false} enableZoom={false}/></>}
export default function FourCube3D(p:{scramble:string;solution:string[];step:number;onAnimating:(v:boolean)=>void;speed:number}){return <Canvas camera={{position:[4.6,3.8,5.6],fov:37}} dpr={[1,1.25]} gl={{antialias:true,alpha:true}} style={{background:"transparent"}}><Scene key={p.scramble} {...p}/></Canvas>}
