"use client";

/** Flash-free 2×2 playback built from the proven permanent-matrix cube system. */
import {Canvas,useFrame} from "@react-three/fiber";
import {OrbitControls,RoundedBox} from "@react-three/drei";
import {memo,useCallback,useEffect,useMemo,useRef} from "react";
import * as THREE from "three";
import {applySequence,solved,toFaceletString} from "@/lib/cube-engine";

type Axis="x"|"y"|"z"; type Cell={x:-1|1;y:-1|1;z:-1|1};
type MoveSpec={axis:Axis;layer:-1|1;angle:number};
type Animation=MoveSpec&{startedAt:number;nextStep:number;cubies:{group:THREE.Group;matrix:THREE.Matrix4}[]};
const COLOR:Record<string,string>={U:"#f7f7f2",R:"#e53935",F:"#24c45a",D:"#ffd21f",L:"#ff7a18",B:"#1464e8"};
const MOVE:Record<string,{axis:Axis;layer:-1|1;clockwise:number}>={U:{axis:"y",layer:1,clockwise:-1},D:{axis:"y",layer:-1,clockwise:1},F:{axis:"z",layer:1,clockwise:-1},B:{axis:"z",layer:-1,clockwise:1},R:{axis:"x",layer:1,clockwise:-1},L:{axis:"x",layer:-1,clockwise:1}};
const CELLS:Cell[]=[]; for(const x of [-1,1] as const)for(const y of [-1,1] as const)for(const z of [-1,1] as const)CELLS.push({x,y,z});
const SPACING=.72;
const invert=(m:string)=>m.endsWith("2")?m:m.endsWith("'")?m[0]:`${m}'`;
const spec=(m:string):MoveSpec=>{const b=MOVE[m[0]],turns=m.endsWith("2")?2:m.endsWith("'")?-1:1;return{...b,angle:b.clockwise*turns*Math.PI/2}};
const rotation=(axis:Axis,a:number)=>axis==="x"?new THREE.Matrix4().makeRotationX(a):axis==="y"?new THREE.Matrix4().makeRotationY(a):new THREE.Matrix4().makeRotationZ(a);
const coordinate=(m:THREE.Matrix4,a:Axis)=>m.elements[a==="x"?12:a==="y"?13:14];
function snap(m:THREE.Matrix4){const n=m.clone(),e=n.elements;for(const i of [0,1,2,4,5,6,8,9,10])e[i]=Math.abs(e[i])<.5?0:e[i]>0?1:-1;e[12]=Math.sign(e[12])*SPACING;e[13]=Math.sign(e[13])*SPACING;e[14]=Math.sign(e[14])*SPACING;e[3]=e[7]=e[11]=0;e[15]=1;return n}
function faceColor(face:string,x:number,y:number,z:number,facelets:string){const i=face==="U"?(z===-1?0:6)+(x===-1?0:2):face==="D"?27+(z===1?0:6)+(x===-1?0:2):face==="F"?18+(y===1?0:6)+(x===-1?0:2):face==="B"?45+(y===1?0:6)+(x===1?0:2):face==="R"?9+(y===1?0:6)+(z===1?0:2):36+(y===1?0:6)+(z===-1?0:2);return COLOR[facelets[i]]}
function Sticker({color,position,rotation=[0,0,0]}:{color:string;position:[number,number,number];rotation?:[number,number,number]}){return <RoundedBox args={[1.28,1.28,.055]} radius={.08} smoothness={3} position={position} rotation={rotation}><meshStandardMaterial color={color} roughness={.34}/></RoundedBox>}
const Cubie=memo(function Cubie({cell,facelets,register}:{cell:Cell;facelets:string;register:(k:string,g:THREE.Group|null)=>void}){const{x,y,z}=cell,key=`${x}:${y}:${z}`,matrix=useMemo(()=>new THREE.Matrix4().makeTranslation(x*SPACING,y*SPACING,z*SPACING),[x,y,z]);const ref=useCallback((g:THREE.Group|null)=>register(key,g),[key,register]);return <group ref={ref} matrixAutoUpdate={false} matrix={matrix}><RoundedBox args={[1.38,1.38,1.38]} radius={.11} smoothness={3}><meshStandardMaterial color="#111318" roughness={.4}/></RoundedBox>{x===1&&<Sticker color={faceColor("R",x,y,z,facelets)} position={[SPACING,0,0]} rotation={[0,Math.PI/2,0]}/>} {x===-1&&<Sticker color={faceColor("L",x,y,z,facelets)} position={[-SPACING,0,0]} rotation={[0,Math.PI/2,0]}/>} {y===1&&<Sticker color={faceColor("U",x,y,z,facelets)} position={[0,SPACING,0]} rotation={[Math.PI/2,0,0]}/>} {y===-1&&<Sticker color={faceColor("D",x,y,z,facelets)} position={[0,-SPACING,0]} rotation={[Math.PI/2,0,0]}/>} {z===1&&<Sticker color={faceColor("F",x,y,z,facelets)} position={[0,0,SPACING]}/>} {z===-1&&<Sticker color={faceColor("B",x,y,z,facelets)} position={[0,0,-SPACING]}/>}</group>});
function Scene({scramble,solution,step,onAnimating,speed}:{scramble:string;solution:string[];step:number;onAnimating:(v:boolean)=>void;speed:number}){const facelets=useMemo(()=>toFaceletString(applySequence(solved(),scramble)),[scramble]);const cubies=useRef(new Map<string,THREE.Group>()),shown=useRef(0),active=useRef<Animation|null>(null),callback=useRef(onAnimating),speedRef=useRef(speed);useEffect(()=>{callback.current=onAnimating},[onAnimating]);useEffect(()=>{speedRef.current=speed},[speed]);const register=useCallback((k:string,g:THREE.Group|null)=>g?cubies.current.set(k,g):cubies.current.delete(k),[]);useEffect(()=>{shown.current=0;active.current=null;callback.current(false)},[facelets]);useEffect(()=>{if(step===shown.current||active.current)return;const forward=step>shown.current,move=forward?solution[shown.current]:invert(solution[shown.current-1]);if(!move)return;const target=spec(move),nextStep=forward?shown.current+1:shown.current-1,selected=Array.from(cubies.current.values()).filter(g=>Math.sign(coordinate(g.matrix,target.axis))===target.layer).map(group=>({group,matrix:group.matrix.clone()}));if(selected.length!==4)return;active.current={...target,startedAt:performance.now(),nextStep,cubies:selected};callback.current(true)},[step,solution]);useFrame(()=>{const a=active.current;if(!a)return;const t=Math.min(1,(performance.now()-a.startedAt)/(460/Math.max(.25,speedRef.current))),e=t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2,r=rotation(a.axis,a.angle*e);for(const c of a.cubies){c.group.matrix.multiplyMatrices(r,c.matrix);c.group.matrixWorldNeedsUpdate=true}if(t>=1){const done=rotation(a.axis,a.angle);for(const c of a.cubies){c.group.matrix.copy(snap(new THREE.Matrix4().multiplyMatrices(done,c.matrix)));c.group.matrixWorldNeedsUpdate=true}shown.current=a.nextStep;active.current=null;callback.current(false)}});return <><hemisphereLight args={["#fff","#18345f",1.5]}/><directionalLight position={[5,8,7]} intensity={1.8}/><group rotation={[-.08,-.08,0]} scale={.9}>{CELLS.map(c=><Cubie key={`${facelets}:${c.x}:${c.y}:${c.z}`} cell={c} facelets={facelets} register={register}/>)}</group><OrbitControls enablePan={false} enableZoom={false}/></>}
export default function PocketCube3D(p:{scramble:string;solution:string[];step:number;onAnimating:(v:boolean)=>void;speed:number}){const key=useMemo(()=>toFaceletString(applySequence(solved(),p.scramble)),[p.scramble]);return <Canvas camera={{position:[4.2,3.4,5],fov:36}} dpr={[1,1.35]} gl={{antialias:true,alpha:true}} style={{background:"transparent"}}><Scene key={key} {...p}/></Canvas>}