"use client";

/** 2×2 solver: corner-only display, verified with the existing cubie engine. */
import dynamic from "next/dynamic";
import {useCallback,useEffect,useRef,useState} from "react";
import Cube from "cubejs";
import {applySequence,isSolved,randomScramble,solved,toFaceletString} from "@/lib/cube-engine";

const PocketCube3D=dynamic(()=>import("./PocketCube3D"),{ssr:false,loading:()=> <div className="grid h-full place-items-center text-sm text-[var(--faint)]">Loading 2×2 cube…</div>});

export default function PocketSolver(){
 const [scramble,setScramble]=useState(""); const [solution,setSolution]=useState<string[]>([]); const [step,setStep]=useState(0); const [ready,setReady]=useState(false); const [status,setStatus]=useState("Preparing solver…"); const [animating,setAnimating]=useState(false); const [playing,setPlaying]=useState(false); const [speed,setSpeed]=useState(1); const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>{const id=setTimeout(()=>{try{Cube.initSolver();setReady(true);setStatus("2×2 solver ready")}catch{setStatus("Solver failed to initialize")}},30);return()=>clearTimeout(id)},[]);
 useEffect(()=>{if(!playing||animating||step>=solution.length){if(step>=solution.length)setPlaying(false);return}timer.current=setTimeout(()=>setStep(v=>Math.min(solution.length,v+1)),Math.max(90,560/speed));return()=>{if(timer.current)clearTimeout(timer.current)}},[playing,animating,step,solution.length,speed]);
 const onAnimating=useCallback((v:boolean)=>setAnimating(v),[]);
 const scrambleCube=()=>{setPlaying(false);const seq=randomScramble(11);setScramble(seq);setSolution([]);setStep(0);setStatus("Pocket Cube scrambled")};
 const solveCube=()=>{if(!ready||!scramble)return;try{const state=applySequence(solved(),scramble);const text=Cube.fromString(toFaceletString(state)).solve().trim();const moves=text?text.split(/\s+/):[];setSolution(moves);setStep(0);setStatus(isSolved(applySequence(state,text))?`Verified — ${moves.length} moves`:"Verification failed")}catch{setStatus("Could not solve this scramble")}};
 const seek=(value:number)=>{if(!animating){setPlaying(false);setStep(value)}};
 return <div className="space-y-4">
  <section className="glass rounded-[22px] p-4"><div className="flex items-center justify-between"><p className="text-xs font-extrabold tracking-[.16em] text-[var(--muted)]">2×2 POCKET CUBE</p><span className="text-xs font-bold text-[var(--green)]">{status}</span></div><p className="mt-3 min-h-12 leading-7">{scramble||"Create a short 2×2 scramble, then solve and play every move."}</p><div className="mt-3 grid grid-cols-2 gap-3"><button onClick={scrambleCube} disabled={animating} className="glass rounded-2xl p-4 font-extrabold disabled:opacity-50">SCRAMBLE 2×2</button><button onClick={solveCube} disabled={!ready||!scramble||animating} className="cta-green rounded-2xl p-4 font-extrabold disabled:opacity-50">SOLVE 2×2</button></div></section>
  <section className="glass rounded-[22px] p-4"><div className="flex items-center justify-between"><p className="text-xs font-extrabold tracking-[.16em] text-[var(--muted)]">VERIFIED SOLUTION</p><span className="text-xs text-[var(--muted)]">{step} / {solution.length}</span></div><div className="mt-3 flex gap-2 overflow-x-auto pb-2">{solution.length?solution.map((m,i)=><button key={`${m}-${i}`} disabled={animating} onClick={()=>seek(i+1)} className={`min-w-11 rounded-xl border p-3 font-extrabold ${i===step-1?"border-[var(--green)] bg-[rgba(52,208,88,.14)]":"border-[var(--border)] bg-black/20"}`}>{m}</button>):<span className="text-[var(--muted)]">—</span>}</div><input aria-label="Solution progress" type="range" min={0} max={Math.max(0,solution.length)} value={step} disabled={!solution.length||animating} onChange={e=>seek(Number(e.target.value))} className="mt-2 w-full"/><div className="mt-3 grid grid-cols-3 gap-2"><button disabled={step===0||animating} onClick={()=>seek(Math.max(0,step-1))} className="glass rounded-xl p-3 font-bold disabled:opacity-40">Previous</button><button disabled={!solution.length} onClick={()=>setPlaying(v=>!v)} className="cta-purple rounded-xl p-3 font-extrabold disabled:opacity-40">{playing?"Pause":"Play"}</button><button disabled={step>=solution.length||animating} onClick={()=>setStep(v=>Math.min(solution.length,v+1))} className="glass rounded-xl p-3 font-bold disabled:opacity-40">Next</button></div><div className="mt-3 flex gap-2">{[.5,1,1.5,2].map(v=><button key={v} onClick={()=>setSpeed(v)} className={`flex-1 rounded-xl border p-2 text-sm font-bold ${speed===v?"border-[var(--green)] text-[var(--green)]":"border-[var(--border)]"}`}>{v}×</button>)}</div></section>
  <section className="glass overflow-hidden rounded-[22px] p-4"><div className="cube-card relative h-[320px] overflow-hidden rounded-[22px]"><div className="platform-ring absolute bottom-[58px] left-1/2 z-[1] h-[66px] w-[230px] -translate-x-1/2 rounded-[50%]"/><div className="absolute inset-0 z-[2]"><PocketCube3D scramble={scramble} solution={solution} step={step} onAnimating={onAnimating} speed={speed}/></div><div className="pointer-events-none absolute bottom-4 left-1/2 z-[3] -translate-x-1/2 whitespace-nowrap text-[13px] font-semibold text-[var(--muted)]">Drag to rotate</div></div></section>
 </div>
}
