"use client";
import { useEffect,useRef,useState } from "react";
import { ChevronLeftIcon,PlayIcon,AutoPlayIcon,PauseIcon } from "./icons";
const MOVES=["R U R' U'","F R U' R'","U R U' R'","L' U' L U","R U2 R'","F U R U'","R' F R F'","U' L' U L","R U R' F'","F R U R'","U2 R U R'","L U L' U'","R' U' R U","F' U' F","R U R' U R U2 R'","U R U' R'","L' U L U'","F R' F' R","R U2 R' U'","R U R' U'"];
const COLORS=["#1667e0","#e6352b","#24b84a","#ffd21f","#ff7a18","#f4f6f8"];
const miniCells=(seed:number)=>Array.from({length:9},(_,i)=>COLORS[(seed*7+i*3)%COLORS.length]);
export default function SolutionStepper(){
 const total=MOVES.length; const [step,setStep]=useState(0); const [playing,setPlaying]=useState(false); const timer=useRef<ReturnType<typeof setInterval>|null>(null);
 useEffect(()=>{if(!playing)return; timer.current=setInterval(()=>setStep(s=>{const n=(s+1)%total;if(n===0)setPlaying(false);return n}),900); return()=>{if(timer.current)clearInterval(timer.current)}},[playing,total]);
 return <div className="glass mt-[18px] rounded-[22px] p-4"><div className="flex items-start justify-between"><div><div className="text-[13px] font-bold text-[var(--purple)]">Next Step</div><div className="mt-0.5 text-[30px] font-extrabold">{MOVES[step]}</div></div><div className="flex items-center gap-[10px]"><div className="grid h-[46px] w-[46px] grid-cols-3 grid-rows-3 gap-0.5 rounded-[9px] bg-[#0c0c0f] p-[3px]">{miniCells(step+1).map((c,i)=><i key={i} className="rounded-[2px]" style={{background:c}}/>)}</div><span className="rounded-full border border-[rgba(139,92,246,.35)] bg-[rgba(139,92,246,.18)] px-[11px] py-1.5 text-xs font-bold">Step {step+1} of {total}</span></div></div><div className="mt-[14px] grid grid-cols-[1fr_1.15fr_1fr] gap-[9px]"><button onClick={()=>setStep(s=>(s-1+total)%total)} className="glass flex items-center justify-center gap-[7px] rounded-[13px] p-[13px]"><ChevronLeftIcon className="h-4 w-4"/>Prev</button><button onClick={()=>setStep(s=>(s+1)%total)} className="cta-purple flex items-center justify-center gap-[7px] rounded-[13px] p-[13px]"><PlayIcon className="h-4 w-4"/>Next</button><button onClick={()=>setPlaying(p=>!p)} className="glass flex items-center justify-center gap-[7px] rounded-[13px] p-[13px]">{playing?<PauseIcon className="h-4 w-4"/>:<AutoPlayIcon className="h-4 w-4"/>}{playing?"Pause":"Auto Play"}</button></div></div>
}
