import Link from "next/link";
import SiteHeader from "@/components/SiteHeader";

const puzzles=[
 {name:"3×3 Rubik's Cube",description:"Full verified solver with polished 3D playback.",status:"READY",href:"/solver/3x3",accent:"text-[var(--green)]",badge:"bg-[rgba(52,208,88,.14)] border-[rgba(52,208,88,.35)]"},
 {name:"2×2 Pocket Cube",description:"Fast corner-only solver with animated playback.",status:"READY",href:"/solver/2x2",accent:"text-[var(--purple)]",badge:"bg-[rgba(139,92,246,.14)] border-[rgba(139,92,246,.35)]"},
 {name:"4×4 Revenge Cube",description:"Playable 4×4 with thumb swipes, highlights, scramble, undo, zoom, and move mode. Full arbitrary-state solver is still in development.",status:"BETA",href:"/solver/4x4",accent:"text-[var(--gold)]",badge:"bg-[rgba(245,185,66,.14)] border-[rgba(245,185,66,.35)]"},
 {name:"10×10 Cube Engine Test",description:"Stress-test our own Cube Labs engine at 10×10 before generalizing the smaller NxN cubes.",status:"TEST",href:"/play/10x10",accent:"text-[#70b7ff]",badge:"bg-[rgba(46,166,255,.14)] border-[rgba(46,166,255,.35)]"},
 {name:"Mirror Cube",description:"3×3 shape-mod mode using size and shape instead of sticker colors.",status:"COMING SOON",accent:"text-[var(--muted)]",badge:"bg-white/5 border-[var(--border)]"},
 {name:"Pyraminx",description:"Fast four-sided twisty-puzzle solving and playback.",status:"COMING SOON",accent:"text-[var(--muted)]",badge:"bg-white/5 border-[var(--border)]"},
 {name:"Skewb",description:"Corner-turning puzzle solver and interactive trainer.",status:"COMING SOON",accent:"text-[var(--muted)]",badge:"bg-white/5 border-[var(--border)]"},
];

export default function SolveHub(){return <main className="app-shell relative min-h-dvh w-full max-w-[460px] overflow-hidden px-5 pb-[calc(28px+env(safe-area-inset-bottom))] pt-[22px]"><div className="orb orb-a"/><div className="orb orb-b"/><div className="relative z-[1]"><SiteHeader/><Link href="/" className="mt-4 inline-flex text-sm font-bold text-[var(--muted)]">← Back to home</Link><section className="mt-5"><p className="text-xs font-extrabold tracking-[.18em] text-[var(--green)]">PUZZLE SOLVERS</p><h1 className="mt-2 text-[39px] font-extrabold leading-[1.02] tracking-[-1px]">What are you<br/><span className="accent-text">solving today?</span></h1><p className="mt-3 max-w-[360px] text-[15px] leading-6 text-[var(--muted)]">Choose your puzzle first. Then enter, scramble, scan, or paste its state inside the correct solver.</p></section><section className="mt-5 space-y-3">{puzzles.map((p,i)=>{const card=<div className="glass rounded-[20px] p-4 transition-transform active:scale-[.99]"><div className="flex items-start justify-between gap-3"><div><p className={`text-[20px] font-extrabold ${p.accent}`}>{p.name}</p><p className="mt-1 text-[14px] leading-5 text-[var(--muted)]">{p.description}</p></div><span className={`shrink-0 rounded-full border px-2.5 py-1 text-[10px] font-extrabold tracking-[.09em] ${p.badge}`}>{p.status}</span></div>{p.href&&<div className="mt-3 flex items-center justify-between text-sm font-extrabold text-[var(--text)]"><span>Open {p.status==="TEST"?"test":"solver"}</span><span>→</span></div>}</div>;return p.href?<Link key={i} href={p.href} className="block">{card}</Link>:<div key={i} className="opacity-70">{card}</div>})}</section><div className="glass mt-5 rounded-[18px] p-4 text-center"><p className="text-sm font-bold text-[var(--text)]">More puzzle engines are coming.</p><p className="mt-1 text-xs leading-5 text-[var(--muted)]">Ready puzzles open now. Beta and test puzzles are clearly labeled so we never pretend a playback demo is a complete solver.</p></div></div></main>}
